// <auto-generated />
using System;
using CareSchedule.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareSchedule.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CareScheduleContext))]
    [Migration("20260421165637_InitialSqlServer")]
    partial class InitialSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareSchedule.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("BookingChannel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("ProviderID");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Booked");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCA2E65367EE");

                    b.HasIndex("RoomId");

                    b.HasIndex("ServiceId");

                    b.HasIndex(new[] { "PatientId" }, "idx_appointment_patient");

                    b.HasIndex(new[] { "ProviderId", "SlotDate" }, "idx_appointment_provider_date");

                    b.HasIndex(new[] { "SiteId", "SlotDate" }, "idx_appointment_site_date");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.AppointmentChange", b =>
                {
                    b.Property<int>("ChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChangeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChangeId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NewValuesJSON");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OldValuesJSON");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ChangeId")
                        .HasName("PK__Appointm__0E05C5B7E222AEF0");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ChangedBy");

                    b.ToTable("AppointmentChange", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("AuditId")
                        .HasName("PK__AuditLog__A17F23B8C0A06457");

                    b.HasIndex(new[] { "UserId", "Timestamp" }, "idx_auditlog_user_time");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.AvailabilityBlock", b =>
                {
                    b.Property<int>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlockID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlockId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("ProviderID");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("BlockId")
                        .HasName("PK__Availabi__1442151191DB61C9");

                    b.HasIndex("ProviderId");

                    b.HasIndex("SiteId");

                    b.ToTable("AvailabilityBlock", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.AvailabilityTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TemplateID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("ProviderID");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<int>("SlotDurationMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("TemplateId")
                        .HasName("PK__Availabi__F87ADD0781DF26FF");

                    b.HasIndex("ProviderId");

                    b.HasIndex("SiteId");

                    b.ToTable("AvailabilityTemplate", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.Blackout", b =>
                {
                    b.Property<int>("BlackoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlackoutID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlackoutId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("BlackoutId")
                        .HasName("PK__Blackout__B868459A22B30DDD");

                    b.HasIndex("SiteId");

                    b.ToTable("Blackout", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.CalendarEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EventID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("ProviderID");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("EventId")
                        .HasName("PK__Calendar__7944C87055CCF4C3");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SiteId");

                    b.ToTable("CalendarEvent", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.CapacityRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<int>("BufferMin")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int?>("MaxApptsPerDay")
                        .HasColumnType("int");

                    b.Property<int?>("MaxConcurrentRooms")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ScopeId")
                        .HasColumnType("int")
                        .HasColumnName("ScopeID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("RuleId")
                        .HasName("PK__Capacity__110458C257D8B4CC");

                    b.ToTable("CapacityRule", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.ChargeRef", b =>
                {
                    b.Property<int>("ChargeRefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChargeRefID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChargeRefId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .IsFixedLength();

                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("ProviderID");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.HasKey("ChargeRefId")
                        .HasName("PK__ChargeRe__635BEE2674BCA41A");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ChargeRef", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.CheckIn", b =>
                {
                    b.Property<int>("CheckInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CheckInID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckInId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<DateTime>("CheckInTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("RoomAssigned")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Waiting");

                    b.Property<string>("TokenNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CheckInId")
                        .HasName("PK__CheckIn__E64976A4A6077818");

                    b.HasIndex("RoomAssigned");

                    b.HasIndex(new[] { "AppointmentId" }, "UQ__CheckIn__8ECDFCA3CEF40C5B")
                        .IsUnique();

                    b.ToTable("CheckIn", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.Holiday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HolidayID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("HolidayId")
                        .HasName("PK__Holiday__2D35D59AE05337BA");

                    b.HasIndex("SiteId");

                    b.ToTable("Holiday", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.LeaveImpact", b =>
                {
                    b.Property<int>("ImpactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImpactID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImpactId"));

                    b.Property<string>("ImpactJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImpactJSON");

                    b.Property<string>("ImpactType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("LeaveId")
                        .HasColumnType("int")
                        .HasColumnName("LeaveID");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.HasKey("ImpactId")
                        .HasName("PK__LeaveImp__2297C5DD3AFBF3F9");

                    b.HasIndex("LeaveId");

                    b.HasIndex("ResolvedBy");

                    b.ToTable("LeaveImpact", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LeaveID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("SubmittedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LeaveId")
                        .HasName("PK__LeaveReq__796DB9793791323E");

                    b.HasIndex(new[] { "UserId", "Status" }, "idx_leaverequest_user");

                    b.ToTable("LeaveRequest", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Unread");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E320934C661");

                    b.HasIndex(new[] { "UserId", "Status" }, "idx_notification_user");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.OnCallCoverage", b =>
                {
                    b.Property<int>("OnCallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OnCallID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OnCallId"));

                    b.Property<int?>("BackupUserId")
                        .HasColumnType("int")
                        .HasColumnName("BackupUserID");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("PrimaryUserId")
                        .HasColumnType("int")
                        .HasColumnName("PrimaryUserID");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("OnCallId")
                        .HasName("PK__OnCallCo__B7A67633E4910699");

                    b.HasIndex("BackupUserId");

                    b.HasIndex("PrimaryUserId");

                    b.HasIndex("SiteId");

                    b.ToTable("OnCallCoverage", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.OpsReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MetricsJSON");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReportId")
                        .HasName("PK__OpsRepor__D5BD48E5832B3C85");

                    b.ToTable("OpsReport", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.Outcome", b =>
                {
                    b.Property<int>("OutcomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OutcomeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutcomeId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<int?>("MarkedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("MarkedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Outcome");

                    b.HasKey("OutcomeId")
                        .HasName("PK__Outcome__113E6AFCC95A983E");

                    b.HasIndex("MarkedBy");

                    b.HasIndex(new[] { "AppointmentId" }, "UQ__Outcome__8ECDFCA383D3EA6B")
                        .IsUnique();

                    b.ToTable("Outcome", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.Provider", b =>
                {
                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("ProviderID");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Credentials")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("ProviderId")
                        .HasName("PK__Provider__B54C689D9E0B5E1B");

                    b.ToTable("Provider", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.ProviderService", b =>
                {
                    b.Property<int>("Psid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PSID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Psid"));

                    b.Property<int?>("CustomBufferAfterMin")
                        .HasColumnType("int");

                    b.Property<int?>("CustomBufferBeforeMin")
                        .HasColumnType("int");

                    b.Property<int?>("CustomDurationMin")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("ProviderID");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("Psid")
                        .HasName("PK__Provider__BC00097697A34DEC");

                    b.HasIndex("ServiceId");

                    b.HasIndex(new[] { "ProviderId", "ServiceId" }, "UQ__Provider__091DD39287307AAF")
                        .IsUnique();

                    b.ToTable("ProviderService", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.PublishedSlot", b =>
                {
                    b.Property<int>("PubSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PubSlotID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PubSlotId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("ProviderID");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.HasKey("PubSlotId")
                        .HasName("PK__Publishe__3CFE843623B80371");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SiteId");

                    b.HasIndex(new[] { "ProviderId", "SlotDate" }, "idx_publishedslot_provider_date");

                    b.ToTable("PublishedSlot", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.ReminderSchedule", b =>
                {
                    b.Property<int>("RemindId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RemindID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemindId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RemindOffsetMin")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("RemindId")
                        .HasName("PK__Reminder__C0874AB5911F58AF");

                    b.HasIndex("AppointmentId");

                    b.ToTable("ReminderSchedule", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.ResourceHold", b =>
                {
                    b.Property<int>("HoldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HoldID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoldId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int")
                        .HasColumnName("ResourceID");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Held");

                    b.HasKey("HoldId")
                        .HasName("PK__Resource__6E24DA24CC77EF60");

                    b.HasIndex("SiteId");

                    b.ToTable("ResourceHold", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("AttributesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AttributesJSON");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("RoomId")
                        .HasName("PK__Room__328639196693EC23");

                    b.HasIndex("SiteId");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.Roster", b =>
                {
                    b.Property<int>("RosterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RosterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RosterId"));

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int?>("PublishedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.HasKey("RosterId")
                        .HasName("PK__Roster__66F6BAAA409A6564");

                    b.HasIndex("PublishedBy");

                    b.HasIndex("SiteId");

                    b.ToTable("Roster", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.RosterAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AssignmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RosterId")
                        .HasColumnType("int")
                        .HasColumnName("RosterID");

                    b.Property<int>("ShiftTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("ShiftTemplateID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Assigned");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("AssignmentId")
                        .HasName("PK__RosterAs__32499E57E16BA1A5");

                    b.HasIndex("RosterId");

                    b.HasIndex("ShiftTemplateId");

                    b.HasIndex(new[] { "UserId", "Date" }, "idx_rosterassignment_user_date");

                    b.ToTable("RosterAssignment", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("BufferAfterMin")
                        .HasColumnType("int");

                    b.Property<int>("BufferBeforeMin")
                        .HasColumnType("int");

                    b.Property<int>("DefaultDurationMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Service__C51BB0EA83FCDB6E");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.ShiftTemplate", b =>
                {
                    b.Property<int>("ShiftTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShiftTemplateID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftTemplateId"));

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("ShiftTemplateId")
                        .HasName("PK__ShiftTem__FA9F704FCAB8D6EC");

                    b.HasIndex("SiteId");

                    b.ToTable("ShiftTemplate", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteId"));

                    b.Property<string>("AddressJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AddressJSON");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasDefaultValue("UTC");

                    b.HasKey("SiteId")
                        .HasName("PK__Site__B9DCB9037BADE0A3");

                    b.ToTable("Site", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.Sla", b =>
                {
                    b.Property<int>("Slaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SLAID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Slaid"));

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Minutes");

                    b.HasKey("Slaid")
                        .HasName("PK__SLA__2848A229D3AB2322");

                    b.ToTable("SLA", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.SystemConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConfigID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Global");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfigId")
                        .HasName("PK__SystemCo__C3BC333C2E0516F0");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "Key" }, "UQ__SystemCo__C41E02899276EC84")
                        .IsUnique();

                    b.ToTable("SystemConfig", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCACA628FF66");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ__User__A9D1053460A18078");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.Waitlist", b =>
                {
                    b.Property<int>("WaitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WaitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WaitId"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Normal");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("ProviderID");

                    b.Property<DateOnly>("RequestedDate")
                        .HasColumnType("date");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.HasKey("WaitId")
                        .HasName("PK__Waitlist__815F96AC4369AB39");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SiteId");

                    b.ToTable("Waitlist", (string)null);
                });

            modelBuilder.Entity("CareSchedule.Models.Appointment", b =>
                {
                    b.HasOne("CareSchedule.Models.User", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK__Appointme__Patie__4D5F7D71");

                    b.HasOne("CareSchedule.Models.Provider", "Provider")
                        .WithMany("Appointments")
                        .HasForeignKey("ProviderId")
                        .IsRequired()
                        .HasConstraintName("FK__Appointme__Provi__4E53A1AA");

                    b.HasOne("CareSchedule.Models.Room", "Room")
                        .WithMany("Appointments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Appointme__RoomI__51300E55");

                    b.HasOne("CareSchedule.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__Appointme__Servi__503BEA1C");

                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("Appointments")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__Appointme__SiteI__4F47C5E3");

                    b.Navigation("Patient");

                    b.Navigation("Provider");

                    b.Navigation("Room");

                    b.Navigation("Service");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.AppointmentChange", b =>
                {
                    b.HasOne("CareSchedule.Models.Appointment", "Appointment")
                        .WithMany("AppointmentChanges")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Appointme__Appoi__56E8E7AB");

                    b.HasOne("CareSchedule.Models.User", "ChangedByNavigation")
                        .WithMany("AppointmentChanges")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Appointme__Chang__58D1301D");

                    b.Navigation("Appointment");

                    b.Navigation("ChangedByNavigation");
                });

            modelBuilder.Entity("CareSchedule.Models.AuditLog", b =>
                {
                    b.HasOne("CareSchedule.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__AuditLog__UserID__14270015");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareSchedule.Models.AvailabilityBlock", b =>
                {
                    b.HasOne("CareSchedule.Models.Provider", "Provider")
                        .WithMany("AvailabilityBlocks")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Availabil__Provi__3C34F16F");

                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("AvailabilityBlocks")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__Availabil__SiteI__3D2915A8");

                    b.Navigation("Provider");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.AvailabilityTemplate", b =>
                {
                    b.HasOne("CareSchedule.Models.Provider", "Provider")
                        .WithMany("AvailabilityTemplates")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Availabil__Provi__3493CFA7");

                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("AvailabilityTemplates")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__Availabil__SiteI__3587F3E0");

                    b.Navigation("Provider");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.Blackout", b =>
                {
                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("Blackouts")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Blackout__SiteID__41EDCAC5");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.CalendarEvent", b =>
                {
                    b.HasOne("CareSchedule.Models.Provider", "Provider")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__CalendarE__Provi__7B264821");

                    b.HasOne("CareSchedule.Models.Room", "Room")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__CalendarE__RoomI__7D0E9093");

                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__CalendarE__SiteI__7C1A6C5A");

                    b.Navigation("Provider");

                    b.Navigation("Room");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.ChargeRef", b =>
                {
                    b.HasOne("CareSchedule.Models.Appointment", "Appointment")
                        .WithMany("ChargeRefs")
                        .HasForeignKey("AppointmentId")
                        .IsRequired()
                        .HasConstraintName("FK__ChargeRef__Appoi__373B3228");

                    b.HasOne("CareSchedule.Models.Provider", "Provider")
                        .WithMany("ChargeRefs")
                        .HasForeignKey("ProviderId")
                        .IsRequired()
                        .HasConstraintName("FK__ChargeRef__Provi__39237A9A");

                    b.HasOne("CareSchedule.Models.Service", "Service")
                        .WithMany("ChargeRefs")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__ChargeRef__Servi__382F5661");

                    b.Navigation("Appointment");

                    b.Navigation("Provider");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CareSchedule.Models.CheckIn", b =>
                {
                    b.HasOne("CareSchedule.Models.Appointment", "Appointment")
                        .WithOne("CheckIn")
                        .HasForeignKey("CareSchedule.Models.CheckIn", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CheckIn__Appoint__671F4F74");

                    b.HasOne("CareSchedule.Models.Room", "RoomAssignedNavigation")
                        .WithMany("CheckIns")
                        .HasForeignKey("RoomAssigned")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__CheckIn__RoomAss__690797E6");

                    b.Navigation("Appointment");

                    b.Navigation("RoomAssignedNavigation");
                });

            modelBuilder.Entity("CareSchedule.Models.Holiday", b =>
                {
                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("Holidays")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Holiday__SiteID__4589517F");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.LeaveImpact", b =>
                {
                    b.HasOne("CareSchedule.Models.LeaveRequest", "Leave")
                        .WithMany("LeaveImpacts")
                        .HasForeignKey("LeaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LeaveImpa__Leave__214BF109");

                    b.HasOne("CareSchedule.Models.User", "ResolvedByNavigation")
                        .WithMany("LeaveImpacts")
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__LeaveImpa__Resol__2334397B");

                    b.Navigation("Leave");

                    b.Navigation("ResolvedByNavigation");
                });

            modelBuilder.Entity("CareSchedule.Models.LeaveRequest", b =>
                {
                    b.HasOne("CareSchedule.Models.User", "User")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__LeaveRequ__UserI__1A9EF37A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareSchedule.Models.Notification", b =>
                {
                    b.HasOne("CareSchedule.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__29E1370A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareSchedule.Models.OnCallCoverage", b =>
                {
                    b.HasOne("CareSchedule.Models.User", "BackupUser")
                        .WithMany("OnCallCoverageBackupUsers")
                        .HasForeignKey("BackupUserId")
                        .HasConstraintName("FK__OnCallCov__Backu__15DA3E5D");

                    b.HasOne("CareSchedule.Models.User", "PrimaryUser")
                        .WithMany("OnCallCoveragePrimaryUsers")
                        .HasForeignKey("PrimaryUserId")
                        .IsRequired()
                        .HasConstraintName("FK__OnCallCov__Prima__14E61A24");

                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("OnCallCoverages")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__OnCallCov__SiteI__13F1F5EB");

                    b.Navigation("BackupUser");

                    b.Navigation("PrimaryUser");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.Outcome", b =>
                {
                    b.HasOne("CareSchedule.Models.Appointment", "Appointment")
                        .WithOne("Outcome")
                        .HasForeignKey("CareSchedule.Models.Outcome", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Outcome__Appoint__6EC0713C");

                    b.HasOne("CareSchedule.Models.User", "MarkedByNavigation")
                        .WithMany("Outcomes")
                        .HasForeignKey("MarkedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Outcome__MarkedB__70A8B9AE");

                    b.Navigation("Appointment");

                    b.Navigation("MarkedByNavigation");
                });

            modelBuilder.Entity("CareSchedule.Models.Provider", b =>
                {
                    b.HasOne("CareSchedule.Models.User", "User")
                        .WithOne("Provider")
                        .HasForeignKey("CareSchedule.Models.Provider", "ProviderId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareSchedule.Models.ProviderService", b =>
                {
                    b.HasOne("CareSchedule.Models.Provider", "Provider")
                        .WithMany("ProviderServices")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProviderS__Provi__2EDAF651");

                    b.HasOne("CareSchedule.Models.Service", "Service")
                        .WithMany("ProviderServices")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__ProviderS__Servi__2FCF1A8A");

                    b.Navigation("Provider");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CareSchedule.Models.PublishedSlot", b =>
                {
                    b.HasOne("CareSchedule.Models.Provider", "Provider")
                        .WithMany("PublishedSlots")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Published__Provi__46B27FE2");

                    b.HasOne("CareSchedule.Models.Service", "Service")
                        .WithMany("PublishedSlots")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__Published__Servi__489AC854");

                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("PublishedSlots")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__Published__SiteI__47A6A41B");

                    b.Navigation("Provider");

                    b.Navigation("Service");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.ReminderSchedule", b =>
                {
                    b.HasOne("CareSchedule.Models.Appointment", "Appointment")
                        .WithMany("ReminderSchedules")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ReminderS__Appoi__308E3499");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("CareSchedule.Models.ResourceHold", b =>
                {
                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("ResourceHolds")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__ResourceH__SiteI__756D6ECB");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.Room", b =>
                {
                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("Rooms")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Room__SiteID__1CBC4616");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.Roster", b =>
                {
                    b.HasOne("CareSchedule.Models.User", "PublishedByNavigation")
                        .WithMany("Rosters")
                        .HasForeignKey("PublishedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Roster__Publishe__0880433F");

                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("Rosters")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__Roster__SiteID__078C1F06");

                    b.Navigation("PublishedByNavigation");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.RosterAssignment", b =>
                {
                    b.HasOne("CareSchedule.Models.Roster", "Roster")
                        .WithMany("RosterAssignments")
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__RosterAss__Roste__0D44F85C");

                    b.HasOne("CareSchedule.Models.ShiftTemplate", "ShiftTemplate")
                        .WithMany("RosterAssignments")
                        .HasForeignKey("ShiftTemplateId")
                        .IsRequired()
                        .HasConstraintName("FK__RosterAss__Shift__0F2D40CE");

                    b.HasOne("CareSchedule.Models.User", "User")
                        .WithMany("RosterAssignments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__RosterAss__UserI__0E391C95");

                    b.Navigation("Roster");

                    b.Navigation("ShiftTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareSchedule.Models.ShiftTemplate", b =>
                {
                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("ShiftTemplates")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__ShiftTemp__SiteI__02C769E9");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.SystemConfig", b =>
                {
                    b.HasOne("CareSchedule.Models.User", "UpdatedByNavigation")
                        .WithMany("SystemConfigs")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__SystemCon__Updat__41B8C09B");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("CareSchedule.Models.Waitlist", b =>
                {
                    b.HasOne("CareSchedule.Models.User", "Patient")
                        .WithMany("Waitlists")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK__Waitlist__Patien__5F7E2DAC");

                    b.HasOne("CareSchedule.Models.Provider", "Provider")
                        .WithMany("Waitlists")
                        .HasForeignKey("ProviderId")
                        .IsRequired()
                        .HasConstraintName("FK__Waitlist__Provid__5D95E53A");

                    b.HasOne("CareSchedule.Models.Service", "Service")
                        .WithMany("Waitlists")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__Waitlist__Servic__5E8A0973");

                    b.HasOne("CareSchedule.Models.Site", "Site")
                        .WithMany("Waitlists")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__Waitlist__SiteID__5CA1C101");

                    b.Navigation("Patient");

                    b.Navigation("Provider");

                    b.Navigation("Service");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CareSchedule.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentChanges");

                    b.Navigation("ChargeRefs");

                    b.Navigation("CheckIn");

                    b.Navigation("Outcome");

                    b.Navigation("ReminderSchedules");
                });

            modelBuilder.Entity("CareSchedule.Models.LeaveRequest", b =>
                {
                    b.Navigation("LeaveImpacts");
                });

            modelBuilder.Entity("CareSchedule.Models.Provider", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AvailabilityBlocks");

                    b.Navigation("AvailabilityTemplates");

                    b.Navigation("CalendarEvents");

                    b.Navigation("ChargeRefs");

                    b.Navigation("ProviderServices");

                    b.Navigation("PublishedSlots");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("CareSchedule.Models.Room", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CalendarEvents");

                    b.Navigation("CheckIns");
                });

            modelBuilder.Entity("CareSchedule.Models.Roster", b =>
                {
                    b.Navigation("RosterAssignments");
                });

            modelBuilder.Entity("CareSchedule.Models.Service", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ChargeRefs");

                    b.Navigation("ProviderServices");

                    b.Navigation("PublishedSlots");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("CareSchedule.Models.ShiftTemplate", b =>
                {
                    b.Navigation("RosterAssignments");
                });

            modelBuilder.Entity("CareSchedule.Models.Site", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AvailabilityBlocks");

                    b.Navigation("AvailabilityTemplates");

                    b.Navigation("Blackouts");

                    b.Navigation("CalendarEvents");

                    b.Navigation("Holidays");

                    b.Navigation("OnCallCoverages");

                    b.Navigation("PublishedSlots");

                    b.Navigation("ResourceHolds");

                    b.Navigation("Rooms");

                    b.Navigation("Rosters");

                    b.Navigation("ShiftTemplates");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("CareSchedule.Models.User", b =>
                {
                    b.Navigation("AppointmentChanges");

                    b.Navigation("Appointments");

                    b.Navigation("AuditLogs");

                    b.Navigation("LeaveImpacts");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Notifications");

                    b.Navigation("OnCallCoverageBackupUsers");

                    b.Navigation("OnCallCoveragePrimaryUsers");

                    b.Navigation("Outcomes");

                    b.Navigation("Provider");

                    b.Navigation("RosterAssignments");

                    b.Navigation("Rosters");

                    b.Navigation("SystemConfigs");

                    b.Navigation("Waitlists");
                });
#pragma warning restore 612, 618
        }
    }
}
